### ISSUE TITLE
Readability of the langage

### ISSUE THREAD

**Issue by xavitator** [Heijix/Warehouse#6] opened 2018-07-06 22:01 UTC
Nut wants be a readable language.
It could impose a format, like '\n' at the end of a list of import, or something like.
It is like to impose a write conventionality.

**Comment by FauconFan** [comment] 2018-07-07 20:39
The language has to be readable. But it allows it, but it don't have to force it... The possibility of the language allows us to write a good configuration file... 

Furthermore, if we force a new line after a list for example, some json files are not accepted by nut anymore.... And our language has to be friendly conciliable with json.

Maybe we can force new line after a import, but that's ugly to force people to configure a file like we thought a configuration should be. Althought, we can compress a nut file in just one line, and the file is still acceptable. (It's not a bug, it's a feature aka Alex)

If it's okay for you, letting you close this issue.

**Closed** 2018-07-07 22:04 UTC
Labels: enhancement
